[package]
name = "deepkey"
version = "0.0.1"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]
name = "deepkey"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
thiserror = "1.0.38"

# temporary fix for compile error in
getrandom = { version = "=0.2.7", features = ["custom"] }
