[package]
name = "deepkey"
description = "DeepKey hApp DNA Coordinator Zome"
version = "0.0.2"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
license = "CAL-1.0"
homepage = "https://github.com/holochain/deepkey"
documentation = "https://github.com/holochain/deepkey"
keywords = [ "holochain", "holo", "deepkey" ]
categories = [ "cryptography", "holochain" ]
edition = "2021"

[lib]
name = "deepkey"
crate-type = [ "cdylib", "rlib" ]
path = "src/lib.rs"

[dependencies]
# Inherit all Holochain dependencies, local types from integrity Zome
deepkey_integrity = {path = "../deepkey_integrity"}
# use whatever serde hdk gives us
serde = "*"
thiserror = "1"
